
default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: mysecretpassword
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: finance_control_api_development


test:
  <<: *default
  database: finance_control_api_test

production:
  <<: *default
  database: finance_control_api_production
  username: finance_control_api
  password: <%= ENV['FINANCE_CONTROL_API_DATABASE_PASSWORD'] %>
